seconds = int(input('Enter number of seconds: '))
print("hoursHappend")
hoursHappend =input(seconds/3600)
print("minsHappend")
minsHappend = input((seconds%3600)/60)
print("secondHappend")
secondHappend = input((seconds%3600)%60)
